title: SNAP
email: snapfse@gmail.com
phone: +12152924418
description: >-
  Special Needs Assistance Program for Social Engagement promotes socialization and friendship-making for neurodiverse communities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://snapfse.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PittTweet
github_username: SNAPFSE

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Include Pages
include:
  - _pages

collections:
  - _people

paginate: 4
paginate_path: "/events/page:num/"
