title: SNAP
email: snapfse@gmail.com
phone: +1 (412)-254-4840
description: >-
  Special Needs Assistance Program for Social Engagement promotes socialization and friendship-making for neurodiverse communities.
tagline: Promoting Friendship in the Neurodiverse Communities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://snapfse.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PittTweet

twitter:
  username: PittTweet
  card: summary

github_username: SNAPFSE
logo: /assets/logo.png

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
# Include Pages
include:
  - _pages

collections:
  - people

paginate: 4
paginate_path: "/blog/page:num/"
